### PR TITLE
Claim task before resolving

### PR DESCRIPTION
**Pull request by rail**
Need to claim the task before marking it resolved.

### CODE REVIEW

**Comment by MihaiTabara** [comment]
@rail do you want me to bump another version here to hold the change? https://pypi.python.org/pypi/tctalker

**Comment by rail** [comment]
No rush, but would be great to bump. I use `master`, not a blocker for me.

**Comment by MihaiTabara** [comment]
bumped - https://pypi.python.org/pypi/tctalker
Thanks again for your patch!

**Comment by rail** [comment]
:+1:

**Pull request merged**
